### ISSUE TITLE
Getting Magisk to work on Chrome OS

### ISSUE THREAD

**Issue by Khang5687** [Gerriarob/arob#2]
I want to use Magisk Manager instead of Super SU to load some modules...Can it be done?

**Comment by Gerriarob** [comment]
no it cant, because its systemless. you can try to copy kernel and initramfs, make a boot.img, copy it to a phone or tablet that have working magisk, open in magisk manager patch file, select your created boot.img and patch, copy boot.img to your machine and extrakt kernel and initramfs. works on android os like openthos, android x86 prime etc, but have not tested on chromeos till now. if i have time, i will test it on chromeos too.

**Comment by Khang5687** [comment]
Or perhaps making Xposed Framework to work on Chrome OS?
